version: '3.8'

services:
  ai_service:
    build:
      context: ./ai_service
      dockerfile: Dockerfile
    container_name: quickcheck-ai-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: quickcheck-backend-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - PYTHON_AI_URL=http://ai_service:8000/analyze
      - JWT_SECRET=quickcheck_ai_docker_jwt_key_2026
    depends_on:
      - ai_service
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: quickcheck-frontend-client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: always
